#!/usr/bin/env python3
import sys
from PySide import QtGui, QtCore
import os

class ImageViewer(QtGui.QWidget):

    def __init__(self):
        super(ImageViewer, self).__init__()
        self.initUI()

    def initUI(self):

        main_layout = QtGui.QVBoxLayout()
        self.setLayout(main_layout)

        self.image = QtGui.QImage(100, 150, QtGui.QImage.Format_ARGB32)
        self.image.scaledToWidth(200)
        self.image.load('/home/ben/code/st/shuttle.jpg')

        self.image_label = QtGui.QLabel("")
        self.image_label.setPixmap(QtGui.QPixmap.fromImage(self.image).scaledToWidth(600))

        button = QtGui.QPushButton('Shuttle', self)
        main_layout.addWidget(button)
        button = QtGui.QPushButton('No Shuttle', self)
        main_layout.addWidget(button)
        main_layout.addWidget(self.image_label)

        self.setGeometry(300, 300, 600, 30)
        self.setWindowTitle('image_viewer')

        QtGui.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Right), self, lambda: self.fire("Right"))
        QtGui.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Left), self, lambda: self.fire("Left"))

        self.show()

    def paintEvent(self, e):
        w = e.rect().width()
        self.image_label.setPixmap(QtGui.QPixmap.fromImage(self.image).scaledToWidth(w-30))

    def fire(self, position):
        print("Firing %s" % position)

def main():

    app = QtGui.QApplication(sys.argv)
    ex = ImageViewer()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
